Improvements to convenience scripts

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -5,7 +5,7 @@ find src/ -iname "*.php" -print0 | xargs -0 -n1 php -l 1>/dev/null || exit $?
 echo -e "\nPHPLINT tests/:"
 find tests/ -iname "*.php" -print0 | xargs -0 -n1 php -l 1>/dev/null || exit $?
 echo -e "\nPHPUNIT:"
-phpunit --stop-on-error --stop-on-failure || exit $?
+phpunit --stop-on-error --stop-on-failure --report-useless-tests --colors=auto || exit $?
 echo -e "\nPHPCS src/:"
 phpcs --warning-severity=0 --standard=PSR2 src/ || exit $?
 echo -e "\nPHPCS tests/:"
@@ -18,3 +18,5 @@ echo -e "\nPHPCPD src/:"
 phpcpd --min-lines=5 --min-tokens=20  --fuzzy -v src/ || exit $?
 echo -e "\nPHPCPD tests/:"
 phpcpd --min-lines=5 --min-tokens=20  --fuzzy tests/ #|| exit $?
+
+echo "\n\n All Done, no failures.\n"
